Repository AY2324S2-CS2113-W12-2/tp, pull requests merged in 2024-03, with the labels that each got.

#59 Add documentation for GoalTask class
  src/main/java/activeedge/task/GoalTask.java
Labels: documentation

#60 WaterTask documentation
  src/main/java/activeedge/task/WaterTask.java
Labels: documentation

#64 Add docs for add goals command
  src/main/java/command/AddGoalsCommand.java
Labels: documentation

#72 Find command
  src/main/java/activeedge/parser/Parser.java
  src/main/java/activeedge/ui/CommandUi.java
  src/main/java/command/FindCommand.java
Labels: enhancement

#84 Goal setting
  src/main/java/command/ShowGoalsCommand.java
Labels: documentation

#86 Bug in storage
  src/main/java/activeedge/Storage.java
Labels: bug

#91 Edits in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#99 Add Clear Command
  src/main/java/activeedge/parser/Parser.java
  src/main/java/activeedge/task/TaskList.java
  src/main/java/activeedge/ui/CommandUi.java
  src/main/java/command/ClearCommand.java
Labels: enhancement

#104 Fixes
  src/main/java/activeedge/Storage.java
  src/main/java/activeedge/parser/Parser.java
  src/main/java/activeedge/userdetails/LogHeight.java
  src/main/java/activeedge/userdetails/LogWeight.java
  src/main/java/activeedge/userdetails/UserDetails.java
  src/main/java/activeedge/userdetails/UserDetailsList.java
  src/main/java/command/ClearCommand.java
Labels: documentation

#106 Edits on User Guide
  docs/UserGuide.md
  src/main/java/activeedge/Storage.java
Labels: documentation

#113 Edit user and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#118 Add new exercise command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  images/Main Component.png
  src/main/java/activeedge/parser/Parser.java
  src/main/java/activeedge/ui/CommandUi.java
  src/main/java/activeedge/ui/GoalsUi.java
  src/main/java/activeedge/ui/HelpUi.java
  src/main/java/command/AddExerciseItemCommand.java
  src/main/java/command/LogExerciseCommand.java
Labels: documentation, enhancement
